var menu = {
	"turkish_doner": "Döner Kebab",
	"turkish_acma": "Açma",
	"turkish_lokum": "Lokum",
	"turkish_dolma": "Dolma",
	"turkish_manti": "Manti",
	"turkish_kofte": "Köfte"
}

var descriptions = {
	"turkish_doner": "<ol><li>Preheat the oven to 350 degrees F(175 degrees C).</li><br><li>Combine flour, oregano, salt, garlic powder, onion powder, Italian seasoning, black pepper, and cayenne pepper in a large bowl. Add ground lamb and thoroughly knead with the flour mixture until thoroughly mixed together, about 3 minutes.</li><br><li>Shape the seasoned ground lamb and place into a loaf pan; set on top of a baking sheet.</li><br><li>Bake in the preheated oven, turning the loaf halfway to ensure even browning, about 1 hour and 20 minutes.</li><br><li>Wrap loaf in aluminium foil and let rest, about 10 minutes. Slice as thinly as possible to make the doner kebab pieces.</li></ol>",
	"turkish_acma": "<ol><li>Preheat oven to 200 C / 400 F.</li><br><li>Combine the yeast with warm water in a bowl, stir well and let the yeast dissolve for a few minutes.</li><br><li>Add the sugar, warm milk and the olive oil to the mixture, stir for the sugar to dissolve.</li><br><li>Sift the flour in a large and stir in the salt. Make a well in the middle and pour in the yeast mixture.</li><br><li>Combine and knead the dough for a few minutes; you will get lovely, soft dough. Cover the dough with a cling film and tea towel and leave to rise at a warm spot (near an oven or in a warm airing cupboards works well) for 2 hours. The dough will double in size.</li><br><li>Once doubled in size, divide the dough into 6 balls. One at a time, roll each dough ball between your palms make 16 cm / 6 inches long. Then swirl and roll and seal the two ends together. Repeat this with the rest of the dough balls.</li><br><li>Place the Acme rolls on a baking paper on a tray, making sure there are minimum 1 inch / 2.5 cm. between each Acme rolls, as they will expand while baking. Brush with the egg mixture and sprinkle sesame seeds over the top if you'd like.</li><br><li>Bake in the preheated oven (200 C/ 400F) for 10 minutes. Then turn the heat down to 190 C/ 375 F and bake for another 10 minutes or until Acma has a rich, golden colour.</li><br><li>Serve warm, afiyet olsun!</li></ol>",
	"turkish_lokum": "<ol><li>Grease the side and bottom of a 9-inch baking pan with butter or shortening. Line with waxed paper and then grease the waxed paper as well.</li><br><li>In a saucepan, combine 1 1/2 cups of the water, the granulated sugar, and lemon juice over medium heat. Stir constantly until the sugar dissolves.</li><br><li>Allow the mixture to boil. Then reduce the heat to low and allow it to simmer until the mixture reaches 240 F on a candy thermometer. Remove from the heat and set aside.</li><br><li>Combine 1 cup of the corn-starch, cream of tartar, and the remaining 2 3/4 cups of water in a saucepan over medium heat. Stir until all the lumps are gone and the mixture begins to boil. Stop stirring when the mixture has a glue-like consistency.</li><br><li>Stir in the sugar and lemon juice mixture. Stir constantly for about 5 minutes. Reduce the heat to low, and allow the mixture to simmer for 1 hour, stirring frequently.</li><br><li>Once the, mixtures has become a golden colour, stir in the rose water. Pour the mixture into the prepared pan. Spread evenly and allow to cool overnight.</li><br><li>The next day, sift together the confectioners' sugar and the remaining 1/4 cup corn-starch.</li><br><li>Invert the baking pan onto a clean counter or table; remove the waxed paper and using an oiled knife, cut the candy into 1-inch pieces.</li><br><li>Place the candy in the bowl with the confectioners' sugar mixture and toss to coat.</li><br><li>Server or store in a container in between layers of waxed or parchment paper. (You don't want the container to be airtight because that can cause sweating).</li></ol>",
	"turkish_dolma": "<ol><li>Wash your peppers and remove the stems by pressing your thumb gently down on the base of the stem. This will cause the stem and base to cave inside the pepper, leaving a perfect hole on the top for stuffing.</li><br><li>Clean out any seeds and white membranes from the inside of the peppers and set them aside.</li><br><li>Put a shallow pan on a medium flame and fry the onions in the olive oil until they are soft and reduced.</li><br><li>Add the pine nuts and brown them along with the onion.</li><br><li>Add all the other dry ingredients and mix well.</li><br><li>Stir in the water and grated tomato and bring it to a boil. Cover and simmer over low heat until the water is almost absorbed.</li><br><li>Once your foiling cools down enough to handle, arrange the empty peppers side-by-side in the bottom of a saucepan. Make sure there is no empty space left between the peppers; if there is, arrange the peppers in a smaller pan so they support each other and stand upright.</li><br><li>With a dessert spoon, fill each pepper with the rice mixture until it reaches the top. Don't pack the filling down or overfill your peppers. The rice will need enough room to expand while it cooks.</li><br><li>Once you've filled the peppers, cover the opening of each with a square of tomato, skin side up. Add enough water to the pan to reach halfway the peppers. Drizzle about two tablespoon of olive oil over the peppers and add some extra salt to the water.</li><br><li>Bring the pan to a gentle boil, then immediately reduce the heat to low. Let the peppers simmer gently with the cover on until most of the water is absorbed.</li><br><li>Remove the pan from the heat and let it continue to steam until it cools to room temperature. If too much condensation forms on the lid, cover the pan with paper towels and close the lid over them, letting the peppers continue to steam.</li><br><li>When the peppers are cool, they will become firmer and easy to remove from the pan. Remove each one gently with your fingers Bing careful not to damage it.</li><br><li>Place the pepper dolma on a decorative serving dish creating a random pile, drizzle them with some more olive oil, and garnish the plate with some chopped, fresh dill weed, if desired.</li></ol>",
	"turkish_manti": "<ol><li>Make the dough:<br>Pour flour and salt into a pile on a work surface or large board. Make a well in the center of the flour and crack the eggs into it. Start with a fork, mixing the eggs and incorporating the flour. When the mixture is too thick for stirring with a fork, start using your hands to mix everything together, gradually adding the water, as you start to knead and press the dough. Knead dough for 8-10 minutes until you get a firm, smooth dough. Cover with a damp cloth and let rest for 30 minutes.</li><br><li>Prepare the filling:<br>While the dough rests, combine lamb, onion, parsley and salt in a small bowl. Set aside.</li><br><li>Prepare the yogurt sauce:<br>Mix all ingredients in a small bowl. Store in the fridge. (Bring to room temp before serving).</li><br><li>Fill Manti:<br>Preheat oven to 325 F. Cut dough into fourths. (Work with one piece at a time, leaving others covered to prevent drying) Roll dough on a floured surface, into a thin sheet, about 1/16 of an inch thick. Use a knife or a pizza cutter to cut into 1 1/2-inch squares. (You can use the edge of a ruler as a guide) Add a small ball of meat - about the size of a chickpea - to the center of each square. Pull the four corners up around the meat and press the four side seams firmly together to seal. Set manti onto a baking sheet, lined with parchment paper. (you'll need two baking sheets) Repeat with the rest of the dough. You should have about 120 manti. Bake for 15 minutes, until it just starts to brown. At this point, you can let the manti cool and store it in the fridge for up to a day or in the freezer for up to two weeks. Allow to come to room temp before continuing.</li><br><li>Prepare the tomato sauce:<br>Cook oil and tomato paste in a small pot over medium low heat, stirring constantly, for about 7 minutes, until you get a deep rich colour and oil is incorporated. Add Aleppo (or paprika and red pepper) and cook, stirring for 30 seconds longer. Remove from heat. Add water and whisk to combine. Set aside. (Reheat just before serving).</li><br><li>Prepare butter sauce:<br>Melt butter in a small saucepan over medium heat. Whisk constantly for 1-3 minutes, until you see little brown flecks appear. Remove from heat. Add olive oil. Set aside.</li><br><li>Bring a large pot of salted water to a boil. Add manti and cook at a gentle boil 10-12 minutes, until tender. Drain. Return manti to its cooking pot. Pour butter sauce over and toss to coat, reheating gently, if need be. Season with salt, to taste. Divide manti between 6 bowls. Spoon on the tomato sauce and yogurt. Drizzle on any extra butter sauce. Sprinkle with spice. Enjoy!</li></ol>",
	"turkish_kofte": "<ol><li>In a food processor add onion cut in four and add parsley. If you are using stale bread soak it in water to soften then squeeze out excess water and add to the onion and parsley mixture. Process until they are fine pieces, avoid over-processing, and don't make it like a pure.</li><br><li>Add the ground meat, spices, and baking soda (If using). Drop 3-4 drops of lemon juice over the baking soda and mix everything by pulsing until is it evenly incorporated.</li><br><li>Dip your hand into the water from time to time and get smaller than mandarin size mixture and first shape into a ball and press it to make a disk. It comes together when cooking and becomes thicker so consider that while shaping.</li><br><li>Cooking the koftes:<br>Heat the cast iron griddle or non-stick frying pan or grill. Brush it with vegetable oil. Add kofte pieces leaving space between them and cook medium heat until both sides and inside are fully cooked.</li><br><li>Meanwhile cut the tomatoes in big wedges and cook on the griddle or grill with green peppers.</li><br><li>Serve the joftes with pilav and grilled veggies. You can also make coban salad, or cacik (yogurt-cucumber sauce) to serve.</li></ol>"
}

var ingredients = {
	"turkish_doner": "1 teaspoon all-purpose flour.<br>1 teaspoon dried oregano.<br>1/2 teaspoon salt.<br>1/2 teaspoon garlic powder.<br>1/2 teaspoon onion powder.<br>1/2 teaspoon dried Italian herb seasoning.<br>1/4 teaspoon ground black pepper.<br>1 1/4 pounds ground lamb.",
	"turkish_acma": "7 grams instant dried yeast.<br>1/2 cup luke warm milk.<br>1/4 cup luke warm water.<br>1 tablespoon sugar.<br>238 grams all-purpose plain flour.<br><br>To glaze:<br>1 egg (beaten).<br>1 tablespoon sesame seeds - optional -",
	"turkish_lokum": "4 1/4 cups water (divided).<br>4 cups granulated sugar.<br>1 tablespoon lemon juice.<br>1 1/4 cups corn-starch (divided).<br>1 teaspoon cream of tartar.<br>1 1/2 tablespoons rose water.<br>1 cup confectioners' sugar.<br>1 teaspoon vegetable oil.",
	"turkish_dolma": "12 small green peppers (with thin skins, suitable for stuffing).<br>1 large onion (finely diced).<br>100 grams dried currants, or dark raisins.<br>60 grams pine nuts.<br>1 large bunch fresh dill weed (sprigs only, thick strems removed).<br>400 grams white rice.<br>3 teaspoons salt.<br>1/2 teaspoon freshly ground black pepper.<br>3 tablespoons cinnamon.<br>2 teaspoons allspice.<br>2 teaspoon sugar.<br>2 cups water.<br>1 medium tomato (grated).<br>1 small tomato (cut into flat squares, for garnish).",
	"turkish_manti": "3 cups flour.<br>2 large eggs.<br>1/2 cup warm water.<br>1/2 teaspoon salt.<br><br>Filling:<br>3/4 pound ground lamb (or beef).<br>1 small onion (grated or finely chopped).<br>4 tablespoons finely chopped parsley.<br>1 tablespoon salt.<br><br>Yogurt sauce:<br>2 cups whole milk Greek yogurt.<br>3 large cloves garlic (pressed).<br>1/2 teaspoon salt.<br><br>Caramelized tomato paste:<br>1 6-ounce can tomato paste (organic is best).<br>4 tablespoons extra virgin olive oil.<br>1 cup water.<br>1 tablespoon ground Aleppo pepper (or substitute 1 1/2 teaspoon sweet paprika plus 1/2 teaspoon crushed red pepper flakes).<br><br>Brown butter sauce:<br>3 tablespoons unsalted butter.<br>3 tablespoons olive oil, and Kosher salt, to taste.<br><br>Spices for sprinkling on top:<br>Sumac (or substitute lemon zest).<br>Dried spearmint (or substitute finely chopped mint leaves).",
	"turkish_kofte": "500 grams ground meat (use 30% lamb if you like and preferably at least 20% fat).<br>2 medium-size onions.<br>4 tbsp ground stale bread/bread crumbs.<br> Handful parsley - optional -<br>1 tsp each black pepper, salt, paprika.<br>1/4 tsp baking soda.<br><br>- optional - 3-4 drops of lemon juice over the baking soda before you add it.<br><br>To serve:<br>1-2 big firm tomatoes.<br>6-8 green sweet peppers.<br>3 tbsp olive oil to brush the griddle or pan."
}

var pictures = {
	"turkish_doner_1": "../../assets/images/turkish/doner-kebab.jpg",
	"turkish_doner_2": "../../assets/images/turkish/doner-kebab_2.jpg",
	"turkish_doner_3": "../../assets/images/turkish/doner-kebab_3.jpg",
	"turkish_acma_1": "../../assets/images/turkish/acma.jpg",
	"turkish_acma_2": "../../assets/images/turkish/acma_2.jpg",
	"turkish_acma_3": "../../assets/images/turkish/acma_3.jpg",
	"turkish_lokum_1": "../../assets/images/turkish/lokum.jpg",
	"turkish_lokum_2": "../../assets/images/turkish/lokum_2.jpg",
	"turkish_lokum_3": "../../assets/images/turkish/lokum_3.jpg",
	"turkish_dolma_1": "../../assets/images/turkish/dolma.jpg",
	"turkish_manti_1": "../../assets/images/turkish/manti.jpg",
	"turkish_kofte_1": "../../assets/images/turkish/kofte.jpg"
}

function getItemRecipe(item) {
	let itemTitle = document.getElementById('item-title');
	let itemDescription = document.getElementById('item-description');
	let itemIngredients = document.getElementById('item-ingredients');
	let itemImages = document.getElementsByClassName('item-image');

	for (i = 0; i < itemImages.length; i++) {
		itemImages[i].src = pictures[item + "_" + (i + 1)];
	}

	itemTitle.textContent = menu[item];
	itemDescription.innerHTML = descriptions[item];
	itemIngredients.innerHTML = ingredients[item];
}